---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidyverse")
library("tidymodels")
library("xgboost")
library("skimr")
library("caret")
library("plyr")
library("car")
```

```{r}
dfTest <- read.csv("TestClean_updated_one.csv")
dfTrain <- read.csv("TrainClean_updated_one.csv")

dfTest <- dfTest %>% select(-host_since) %>% select(-region) %>% select(-maximum_nights) %>% select(-minimum_nights)%>% select(-extra_people) %>% select(-guests_included)%>% select(-host_listings_count) %>% select(-cleaning_fee) 

dfTrain <- dfTrain %>% select(-host_since) %>% select(-X) %>% select(-region) %>% select(-maximum_nights) %>% select(-minimum_nights) %>% select(-extra_people) %>% select(-guests_included) %>% select(-host_listings_count)%>% select(-cleaning_fee)   

#dfTrain <- as.matrix(dfTrain)

colnames(dfTrain)

```

```{r}
colnames(dfTest)
```



```{r}
dfTrain$high_booking_rate <- as.factor(dfTrain$high_booking_rate)

dfTrain$property_type <- as.numeric(dfTrain$property_type)
dfTest$property_type <- as.numeric(dfTest$property_type)

dfTrain$state <- as.numeric(dfTrain$state)
dfTest$state <- as.numeric(dfTest$state)

dfTrain$city <- as.numeric(dfTrain$city)
dfTest$city <- as.numeric(dfTest$city)

dfTrain$cancellation_policy <- as.numeric(dfTrain$cancellation_policy)
dfTest$cancellation_policy <- as.numeric(dfTest$cancellation_policy)

dfTrain$price <- as.numeric(dfTrain$price)
dfTest$price <- as.numeric(dfTest$price)

```


```{r}
skim(dfTrain)
```

```{r}
skim(dfTest)
```

```{r}
set.seed(10000)  # For reproducibility
# Create index for testing and training data
inTrain <- createDataPartition(y = dfTrain$high_booking_rate, p = 0.7, list = FALSE)
# subset power_plant data to training
training <- dfTrain[inTrain,]
# subset the rest to test
testing <- dfTrain[-inTrain,]
```

```{r}
X_train = xgb.DMatrix(as.matrix(training %>% select(-high_booking_rate)))
y_train = training$high_booking_rate
X_test = xgb.DMatrix(as.matrix(testing %>% select(-high_booking_rate)))
y_test = testing$high_booking_rate
```

```{r}
xgb_trcontrol = trainControl(
  method = "cv",
  number = 5,  
  allowParallel = TRUE,
  verboseIter = FALSE,
  returnData = FALSE
)
```

```{r}
xgbGrid <- expand.grid(nrounds = c(100,200),  # this is n_estimators in the python code above
                       max_depth = c(10, 15, 20, 25),
                       colsample_bytree = seq(0.5, 0.9, length.out = 5),
                       ## The values below are default values in the sklearn-api. 
                       eta = 0.1,
                       gamma=0,
                       min_child_weight = 1,
                       subsample = 1
                      )
```

```{r}
set.seed(0) 
xgb_model = train(
  X_train, y_train,  
  trControl = xgb_trcontrol,
  tuneGrid = xgbGrid,
  method = "xgbTree"
)
```

```{r}

resultsXG <-
  xgb_model %>% 
    predict(dfTest, type= 'prob') %>%      
    bind_cols(dfTest, predictedProb=.)
resultsXG

```

```{r}
out10 <- resultsXG %>% select(id,`1`)

colnames(out10) <- c("id","high_booking_rate")

write.csv(out10,"out10.csv",row.names = FALSE)

out10
```
